# AUTOGENERATED! DO NOT EDIT! File to edit: bear-me.ipynb.

# %% auto 0
__all__ = ['categories', 'model_name', 'learn', 'image', 'label', 'examples', 'intf', 'classify_image']

# %% bear-me.ipynb 36
import gradio as gr
from fastai.vision.all import *

categories = ('black', 'grizzly', 'teddy')

def classify_image(img):
    pred, pred_idx, probs = learn.predict(img)
    return dict(zip(categories, map(float, probs)))

model_name = 'ma_nigga.pkl'  # Ensure this matches your model file name
learn = load_learner(model_name)

image = gr.Image()
label = gr.Label()
examples = ['grizzly1.jpg', 'grizzly2.jpg', 'bear1.jpg', 'bear2.png']

intf = gr.Interface(fn=classify_image, inputs=image, outputs=label, examples=examples)
intf.launch()


